//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NickStageHazardRemover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NickStageHazardRemover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkSerialize
        ///VERSION_0
        ///175
        ///5
        ///21
        ///15
        ///29
        ///0
        ///6
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///17
        ///0
        ///2
        ///0
        ///8
        ///0
        ///14
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///5
        ///2
        ///0
        ///7
        ///0
        ///2
        ///0
        ///13
        ///0
        ///13
        ///0
        ///15
        ///0
        ///14
        ///0
        ///2
        ///0
        ///3
        ///27
        ///0
        ///0
        ///0
        ///0
        ///9
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///58
        ///0
        ///7
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///17
        ///0
        ///1
        ///0
        ///11
        ///0
        ///0
        ///21
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///2
        ///2
        ///0
        ///0
        ///0
        ///2
        ///0
        ///17
        ///0
        ///1
        ///0
        ///12
        ///0
        ///3
        ///11
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///14
        ///0
        ///2
        ///0
        ///0
        ///10
        ///0
        ///0
        ///0
        ///9
        ///0
        ///0
        ///7
        ///9
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///6
        ///2
        ///0
        ///7
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string spawn_jungle_log_new {
            get {
                return ResourceManager.GetString("spawn_jungle_log_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkSerialize
        ///VERSION_0
        ///61
        ///2
        ///31
        ///6
        ///10
        ///0
        ///1
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///2
        ///69
        ///2
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///16
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///7
        ///0
        ///69
        ///2
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///16
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///7
        ///0
        ///0
        ///1
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///0
        ///OnWaitForInput
        ///
        ///log
        ///log_mid
        ///spawntype
        ///log_bottom
        ///0
        ///1
        ///2
        ///2
        ///3
        ///4
        ///2
        ///2
        ///5
        ///4
        ///.
        /// </summary>
        public static string stage_narrator_jungle_new {
            get {
                return ResourceManager.GetString("stage_narrator_jungle_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkSerialize
        ///VERSION_0
        ///470
        ///8
        ///56
        ///24
        ///75
        ///0
        ///8
        ///0
        ///1
        ///0
        ///0
        ///1
        ///0
        ///13
        ///0
        ///0
        ///1
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///3
        ///2
        ///0
        ///7
        ///0
        ///8
        ///0
        ///58
        ///0
        ///7
        ///11
        ///0
        ///12
        ///0
        ///6
        ///0
        ///11
        ///0
        ///11
        ///0
        ///1
        ///0
        ///12
        ///0
        ///3
        ///17
        ///0
        ///1
        ///0
        ///12
        ///0
        ///1
        ///0
        ///0
        ///0
        ///2
        ///0
        ///7
        ///0
        ///8
        ///0
        ///11
        ///0
        ///12
        ///0
        ///6
        ///0
        ///12
        ///0
        ///2
        ///58
        ///0
        ///0
        ///13
        ///0
        ///0
        ///1
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///4
        ///2
        ///0
        ///7
        ///0
        ///8
        ///0
        ///58
        ///0
        ///7
        ///10
        ///0
        ///11
        ///0
        ///12
        ///0
        ///6
        ///0
        ///11
        ///0
        ///11
        ///0
        ///1
        ///0
        ///12
        ///0
        ///3
        ///17
        ///0
        ///1
        ///0
        ///12
        ///0
        ///1
        ///0
        ///0
        ///0
        ///2
        ///0
        ///7
        ///0
        ///8
        ///0
        ///11
        ///0
        ///12
        ///0
        ///6
        ///0
        ///12
        ///0
        ///2
        ///58
        ///0
        ///0
        ///13
        ///0
        ///0
        ///1
        ///0
        ///0
        ///1
        ///0
        ///12
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string stage_snake_dump_new {
            get {
                return ResourceManager.GetString("stage_snake_dump_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BulkSerialize
        ///VERSION_0
        ///16
        ///1
        ///1
        ///3
        ///4
        ///0
        ///2
        ///0
        ///0
        ///0
        ///0
        ///1
        ///0
        ///12
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///OnWaitForInput
        ///
        ///world_state
        ///0
        ///1
        ///2
        ///1
        ///.
        /// </summary>
        public static string stage_static {
            get {
                return ResourceManager.GetString("stage_static", resourceCulture);
            }
        }
    }
}
